### ISSUE TITLE
Put storage class after colon

### ISSUE THREAD

**Issue by woodrowbarlow** [jdpage/jeff65#12]
right now a let declaration looks like this:

    let mut x: u16 = 0

we've agreed that it's easier to read if the storage class modifies the type rather than the name:

    let x: mut u16 = 0

**Comment by woodrowbarlow** [comment]
re-opened for discussion

**Comment by jdpage** [comment]
note: this was re-opened for discussion because I decided that under this scheme, a mutable binding to a mutable pointer would end up looking like this:

    let x: mut &mut u8 = ...

rather than this:

    let mut x: &mut u8 = ...

Also, I'm beginning to think that storage classes really do apply to the *binding*, rather than the *value*. If I have this:

    let x: u8 = 42
    let mut y: u8 = x

... then that's legal; mutability in the type really only applies to pointers and whether you can mutate the pointed-to value, which is expressed with the `&mut ...` pointer type.

**Comment by woodrowbarlow** [comment]
@kpmgeek do you have any input?

**Comment by woodrowbarlow** [comment]
i agree with jonathan's latest comment.
